name: shaghaf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.14
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.0
  get_storage: ^2.1.1
  supabase_flutter: ^2.8.0
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  flutter_bloc: ^8.1.6
  pinput: ^5.0.0
  hugeicons: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - 'assets/'
  - 'assets/images/'
  - '.env'

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
  
    - family: Mirza
      fonts:
        - asset: assets/fonts/Mirza-Bold.ttf
        - asset: assets/fonts/Mirza-SemiBold.ttf
        - asset: assets/fonts/Mirza-Medium.ttf
        - asset: assets/fonts/Mirza-Regular.ttf