name: shaghaf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.14
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.0
  get_storage: ^2.1.1
  supabase_flutter: ^2.8.0
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  flutter_bloc: ^8.1.6
  pinput: ^5.0.0
  flutter_multi_select_items: ^0.4.3
  hugeicons: ^0.0.7
  device_preview: ^1.2.0
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  otp_timer_button: ^1.1.1
  custom_radio_grouped_button: ^2.2.1
  getwidget: ^4.0.0
  moyasar: ^2.0.13
  intl: ^0.19.0
  lottie: ^3.1.3
  qr_flutter: ^4.1.0
  barcode_scan2: ^4.3.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shimmer: ^3.0.0
  custom_rating_bar: ^3.0.0
  onesignal_flutter: ^5.2.6
  http: ^1.2.2
  emailjs: ^4.0.0
  url_launcher: ^6.3.1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - .env
    - assets/images/categories/
    - assets/images/categories/icons/
    - assets/lottie/
    - assets/translations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
  
    - family: Mirza
      fonts:
        - asset: assets/fonts/Mirza-Bold.ttf
        - asset: assets/fonts/Mirza-SemiBold.ttf
        - asset: assets/fonts/Mirza-Medium.ttf
        - asset: assets/fonts/Mirza-Regular.ttf